### ISSUE TITLE
'Move in date' error on create mock data

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#266]
When creating mock data, I get the following error:

```javascript
Error: Move in is not a valid date in residencies insert
    at getErrorObject (packages/aldeed:collection2-core/collection2.js:498:17)
    at doValidate (packages/aldeed:collection2-core/collection2.js:470:13)
    at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2-core/collection2.js:195:14)
    at packages/erikpel:wellbeing-mock-data/wellbeing-mock-data.js:195:15
    at Array.forEach (<anonymous>)
    at createMockResidency (packages/erikpel:wellbeing-mock-data/wellbeing-mock-data.js:179:13)
    at MethodInvocation.createMockData (packages/erikpel:wellbeing-mock-data/wellbeing-mock-data.js:208:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
    at resolve (packages/ddp-server/livedata_server.js:1684:36)
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
    at Server.call (packages/ddp-server/livedata_server.js:1604:17)
    at repl:1:-54
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at evalCommandPromise.then (packages/shell-server/shell-server.js:246:21)
    at /home/brylie/.meteor/packages/promise/.0.10.2.1e6t655.x2xs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/brylie/.meteor/packages/promise/.0.10.2.1e6t655.x2xs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1635:14)
    at Server.call (packages/ddp-server/livedata_server.js:1604:17)
    at repl:1:-54
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at evalCommandPromise.then (packages/shell-server/shell-server.js:246:21)
    at /home/brylie/.meteor/packages/promise/.0.10.2.1e6t655.x2xs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by brylie** [comment]
cc: @ErikPel
