### ISSUE TITLE
Cannot destructure property `isActive` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#522]
When starting the project without any registered users, the following traceback can be seen in the console:

```
Exception while invoking method 'login' TypeError: Cannot destructure property `isActive` of 'undefined' or 'null'.
I20200305-10:17:41.675(2)?     at lib/accounts.js:44:32
I20200305-10:17:41.675(2)?     at packages/callback-hook/hook.js:130:22
I20200305-10:17:41.675(2)?     at _validateLoginHook.each.callback (packages/accounts-base/accounts_server.js:154:15)
I20200305-10:17:41.675(2)?     at Hook.each (packages/callback-hook/hook.js:108:15)
I20200305-10:17:41.675(2)?     at AccountsServer._validateLogin (packages/accounts-base/accounts_server.js:151:29)
I20200305-10:17:41.675(2)?     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:338:10)
I20200305-10:17:41.676(2)?     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)
I20200305-10:17:41.676(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20200305-10:17:41.676(2)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20200305-10:17:41.676(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200305-10:17:41.676(2)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20200305-10:17:41.676(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200305-10:17:41.676(2)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20200305-10:17:41.676(2)?     at new Promise (<anonymous>)
I20200305-10:17:41.677(2)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20200305-10:17:41.677(2)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by shailee-m** [comment]
@brylie this issue is not reproducing anymore.
