### ISSUE TITLE
TypeError: jsdoc2md.render is not a function

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#538]
When deploying the project to a production server, not in development mode, the following error prevents the deployment:

```
TypeError: jsdoc2md.render is not a function
            at module (docToMarkdown.js:4:10)
            at fileEvaluate (packages/modules-runtime.js:336:7)
            at Module.require (packages/modules-runtime.js:238:14)
            at require (packages/modules-runtime.js:258:21)
            at /built_app/programs/server/app/app.js:4790:1
            at /built_app/programs/server/boot.js:398:38
            at Array.forEach (<anonymous>)
            at /built_app/programs/server/boot.js:226:21
            at /built_app/programs/server/boot.js:461:7
            at Function.run (/built_app/programs/server/profile.js:280:14)
            at /built_app/programs/server/boot.js:460:13
```

It seems related to the recent JSDoc additions.

https://github.com/GeriLife/wellbeing/blob/ae6b6054c70737f30fe45019f015cb28ed6d2daf/app/docToMarkdown.js#L4

Is there a way that this file could only be envoked in development mode?

## Task
- [x] resolve the issue so the project can be deployed in production

**Comment by brylie** [comment]
In effect, this code should not run on a production server. The jsdoc2md dependency is marked as a "dev dependency", but the code is still being parsed or invoked during the deployment process.

**Comment by brylie** [comment]
I have been able to deploy successfully by commenting out the code in the file and saving. So, there should be some way to only include this file in a development environment and not in the deployment bundle.

**Comment by brylie** [comment]
One approach might be to add this file to a `.meteorignore` file:

https://stackoverflow.com/a/46825213/1191545
